I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2102, in script
    python:
  File "game/script.rpy", line 2104, in <module>
    renpy.jump(gym_day_halloween_good)
NameError: name 'gym_day_halloween_good' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2102, in script
    python:
  File "/Applications/renpy-7.3.0-sdk/renpy/ast.py", line 912, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-7.3.0-sdk/renpy/python.py", line 1959, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 2104, in <module>
    renpy.jump(gym_day_halloween_good)
NameError: name 'gym_day_halloween_good' is not defined

Darwin-18.6.0-x86_64-i386-64bit
Ren'Py 7.3.0.271
Love Hunt 1.1
Sun Jun 30 16:53:17 2019
